name: ruang
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ditambahkan untuk lokalisasi internal Flutter
  flutter_localizations:
    sdk: flutter

  # Firebase & Auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  flip_card: ^0.7.0
  cloud_firestore: ^4.17.5
  intl: ^0.20.2
  http: ^1.4.0
  skeletonizer: ^2.1.0+1
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.2
  midtrans_sdk: ^1.0.1
  flutter_dotenv: ^5.2.1
  js: ^0.7.2
  google_generative_ai: ^0.4.7
  firebase_remote_config: ^4.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro1.json
    - assets/images/intro2.json
    - assets/images/intro3.json
    - assets/images/logo RUANG.png
    - assets/images/background.jpg
    - assets/images/error_animation.json
    - assets/images/loading_animation.json
    - assets/images/failed.json
    - .env
 