// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOM0NBew7TFP0J6SA4FnuUTXl2QeEgtVk',
    appId: '1:522301218733:web:653b9eb97d8efbf1988b24',
    messagingSenderId: '522301218733',
    projectId: 'ruang-app-668eb',
    authDomain: 'ruang-app-668eb.firebaseapp.com',
    storageBucket: 'ruang-app-668eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLp_V0XxsZe5RkK_wcGxwQBVYXLdPj7cY',
    appId: '1:522301218733:android:e59bc394e1cd477b988b24',
    messagingSenderId: '522301218733',
    projectId: 'ruang-app-668eb',
    storageBucket: 'ruang-app-668eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQ5ySQAmtE0UMIFAiCfV0doAv1ZZR6oA',
    appId: '1:522301218733:ios:3827ba1e4b8b22fe988b24',
    messagingSenderId: '522301218733',
    projectId: 'ruang-app-668eb',
    storageBucket: 'ruang-app-668eb.firebasestorage.app',
    iosBundleId: 'com.example.ruang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlQ5ySQAmtE0UMIFAiCfV0doAv1ZZR6oA',
    appId: '1:522301218733:ios:3827ba1e4b8b22fe988b24',
    messagingSenderId: '522301218733',
    projectId: 'ruang-app-668eb',
    storageBucket: 'ruang-app-668eb.firebasestorage.app',
    iosBundleId: 'com.example.ruang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOM0NBew7TFP0J6SA4FnuUTXl2QeEgtVk',
    appId: '1:522301218733:web:d27474dd86216112988b24',
    messagingSenderId: '522301218733',
    projectId: 'ruang-app-668eb',
    authDomain: 'ruang-app-668eb.firebaseapp.com',
    storageBucket: 'ruang-app-668eb.firebasestorage.app',
  );
}
